"""create statement_scans table

Revision ID: ce41d7beedb9
Revises: i9j0k1l2m3n4
Create Date: 2026-09-19 00:22:27.723777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce41d7beedb9'
down_revision: Union[str, None] = 'i9j0k1l2m3n4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statement_scans',
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=256), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('as_of', sa.Date(), nullable=True),
    sa.Column('ocr_raw_json', sa.Text(), nullable=True),
    sa.Column('ocr_model', sa.String(length=128), nullable=True),
    sa.Column('ocr_status', sa.String(length=16), nullable=False),
    sa.Column('ocr_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statement_scans_sha256'), 'statement_scans', ['sha256'], unique=True)
    op.create_index(op.f('ix_budgets_year_month'), 'budgets', ['year_month'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budgets_year_month'), table_name='budgets')
    op.drop_index(op.f('ix_statement_scans_sha256'), table_name='statement_scans')
    op.drop_table('statement_scans')
    # ### end Alembic commands ###
